import { writeFileSync, mkdirSync, existsSync, readFileSync } from "fs"
import { join } from "path"
import { collectProjectFiles, isEmptyProject } from "../collect.js"
import { readState } from "../state.js"
import { updateManifest } from "../manifest.js"
import {
  buildEmptyProjectCommand,
  buildAtomicSteps,
  buildOrchestratorCommand,
  buildBootstrapSync,
} from "../builder.js"
import { createSnapshot, collectFilesForSnapshot } from "../snapshot.js"
import { estimateTokens, estimateCost, formatCost, getTokenHookScript } from "../tokens.js"
import { c, section } from "../output.js"
import { ensureConfig } from "../config.js"
import { applyTemplate } from "./export.js"

function ensureDir(dir: string): void {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

/** Install bootstrap slash commands so all operations work from within Claude Code */
function installBootstrapCommands(dir: string): void {
  const cmds: Record<string, string> = {
    "stack-add.md": `<!-- stack-add: bootstrap — regenerated by npx claude-setup add -->

> **Step 1:** Ask the user: "What do you want to add to your Claude Code setup?"
> **Step 2:** After the user responds, run: \`npx claude-setup add "<their exact answer>"\`
> **Step 3:** Re-read this file (\`.claude/commands/stack-add.md\`) — it was just regenerated with full marketplace instructions.
> **Step 4:** Follow the marketplace install instructions in the updated file. Do NOT ask clarifying questions — go straight to searching and installing.

**IMPORTANT — marketplace-first approach:**
- After Step 3, the regenerated file contains a 4-step marketplace search flow. Follow it AUTOMATICALLY.
- Do NOT ask the user "do you mean X or Y?" — search the marketplace for ALL interpretations.
- Do NOT suggest manual installation steps — execute the curl/install commands yourself.
- The goal is ZERO friction: user says what they want → you search → you install → done.
- Only ask the user if the marketplace returns multiple equally-valid matches and you need to pick one.
`,
    "stack-status.md": `<!-- stack-status: show project state -->

Run this command and display the output to the user:
\`\`\`bash
npx claude-setup status
\`\`\`
No further action needed — the output IS the status.
`,
    "stack-doctor.md": `<!-- stack-doctor: validate environment -->

> **Step 1:** Run: \`npx claude-setup doctor\`
> **Step 2:** Show the output to the user.
> **Step 3:** If any issues are found (lines with red or warning markers), ask: "Want me to auto-fix these?"
> **Step 4:** If yes, run: \`npx claude-setup doctor --fix\`
`,
    "stack-restore.md": `<!-- stack-restore: time-travel to any snapshot -->

> **Step 1:** Run: \`npx claude-setup restore --list\` to show the snapshot timeline.
> **Step 2:** Show the timeline to the user and ask: "Which snapshot do you want to restore to? (enter the ID)"
> **Step 3:** After the user picks an ID, run: \`npx claude-setup restore --id "<snapshot-id>"\`
> **Step 4:** Show the result.
`,
    "stack-remove.md": `<!-- stack-remove: bootstrap — regenerated by npx claude-setup remove -->

> **Step 1:** Ask the user: "What do you want to remove from your Claude Code setup?"
> **Step 2:** After the user responds, run: \`npx claude-setup remove "<their exact answer>"\`
> **Step 3:** Re-read this file (\`.claude/commands/stack-remove.md\`) — it was just regenerated.
> **Step 4:** Follow the instructions in the updated file.
`,
  }

  for (const [filename, content] of Object.entries(cmds)) {
    const filepath = join(dir, filename)
    // Don't overwrite if already populated with real content (e.g., after an add/remove run)
    if (existsSync(filepath)) {
      const existing = readFileSync(filepath, "utf8")
      if (!existing.includes("bootstrap")) continue
    }
    writeFileSync(filepath, content, "utf8")
  }
}

/** Install the marketplace-fetcher subagent so /stack-add can spawn it */
export function installMarketplaceFetcher(cwd: string = process.cwd()): void {
  const agentsDir = join(cwd, ".claude", "agents")
  ensureDir(agentsDir)
  const filepath = join(agentsDir, "marketplace-fetcher.md")
  // Always overwrite — this is a system agent, not user-authored
  writeFileSync(filepath, `---
name: marketplace-fetcher
description: Fetches skills and agents from all 4 marketplace catalogs. Spawned automatically by stack-add. Runs in isolation, writes to disk, returns only the install confirmation.
tools: Bash
model: haiku
---

You are a marketplace fetch agent. You receive a prompt containing marketplace instructions with bash code blocks. Your job is to RUN those bash commands, use the output to find matching files, download them, and confirm the install.

## CRITICAL RULES — read before doing anything

1. **You MUST run curl commands.** Your entire purpose is to fetch from remote catalogs. If you finish without running at least 3 curl commands, you have failed.
2. **NEVER skip to custom creation early.** You may only create custom content after you have attempted ALL catalog steps with real curl calls and each one returned empty or errored.
3. **Use relative paths only.** Never prepend \`cd /some/path &&\` to commands. You are already in the project directory.
4. **Pipe curl output through node parsers.** Never let raw JSON/README enter the context. Every curl MUST pipe through \`| node -e "..."\` to extract only the lines you need.
5. **A curl failure or empty result means: try the next step.** It does NOT mean stop. Log what failed in one line, then continue to the next step.
6. **Fill in template variables.** The instructions contain placeholder variables like \`CATEGORY="09-meta-orchestration"\` and \`SKILL_DIR="matched-directory"\`. Replace these with ACTUAL values from the previous step's output.
7. **Verify downloads.** After every curl -o, check the file exists and has >50 characters of content. If empty or stub: delete it, log failure, continue.

## How to execute the instructions

Your prompt contains numbered STEPs with bash code blocks. For each STEP:

1. Run the first bash command (the catalog listing/search)
2. Read the output — it shows available files/directories
3. Pick the entry that best matches the user's request
4. Substitute that entry name into the download command
5. Run the download command
6. Verify the downloaded file has real content
7. If it works → return the success line. If not → go to next STEP.

## Return format

Return exactly ONE line:
- \`INSTALLED .claude/agents/<file> <bytes>b\` or
- \`INSTALLED .claude/skills/<dir>/SKILL.md <bytes>b\` or
- \`CREATED .claude/agents/<file> <bytes>b\` (only after ALL catalogs exhausted) or
- \`CREATED .claude/skills/<dir>/SKILL.md <bytes>b\` or
- \`FAILED no match in any catalog and custom creation not possible\`

## Example of correct behavior

If the instructions say:
\`\`\`bash
curl -sf "https://api.github.com/repos/X/Y/contents/categories/03-infrastructure" | node -e "..."
\`\`\`
And the output shows: \`docker-compose-agent.md\`, \`kubernetes-agent.md\`, \`terraform-agent.md\`

Then for the download command that says \`AGENT_FILE="matched-agent.md"\`, you substitute:
\`\`\`bash
AGENT_FILE="kubernetes-agent.md"
curl -sf "https://raw.githubusercontent.com/X/Y/main/categories/03-infrastructure/kubernetes-agent.md" -o ".claude/agents/kubernetes-agent.md"
\`\`\`

Then verify: \`wc -c ".claude/agents/kubernetes-agent.md"\`

Now execute the instructions in your prompt. Start with STEP 1 immediately.
`, "utf8")
}

function installTokenHook(cwd: string = process.cwd()): void {
  // Write the hook script
  const hooksDir = join(cwd, ".claude", "hooks")
  if (!existsSync(hooksDir)) mkdirSync(hooksDir, { recursive: true })
  writeFileSync(join(hooksDir, "track-tokens.cjs"), getTokenHookScript(), "utf8")

  // Merge Stop hook into settings.json
  const settingsPath = join(cwd, ".claude", "settings.json")
  let settings: Record<string, unknown> = {}
  if (existsSync(settingsPath)) {
    try { settings = JSON.parse(readFileSync(settingsPath, "utf8") ?? "{}") } catch {}
  }

  const hookEntry = {
    hooks: [{ type: "command", command: "node \".claude/hooks/track-tokens.cjs\"" }]
  }

  // Merge into settings.hooks.Stop
  if (!settings.hooks) settings.hooks = {}
  const hooks = settings.hooks as Record<string, unknown[]>
  if (!Array.isArray(hooks.Stop)) hooks.Stop = []

  // Only add if not already present
  const alreadyPresent = (hooks.Stop as Array<Record<string, unknown>>).some(e =>
    Array.isArray(e.hooks) && (e.hooks as Array<Record<string, unknown>>).some(
      (h: Record<string, unknown>) => typeof h.command === "string" && h.command.includes("track-tokens")
    )
  )
  if (!alreadyPresent) {
    hooks.Stop.push(hookEntry)
    if (!existsSync(join(cwd, ".claude"))) mkdirSync(join(cwd, ".claude"), { recursive: true })
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8")
  }
}

export async function runInit(opts: { dryRun?: boolean; template?: string } = {}): Promise<void> {
  const dryRun = opts.dryRun ?? false

  // Feature H: --template flag — apply a template instead of scanning
  if (opts.template) {
    console.log(`Applying template: ${c.cyan(opts.template)}\n`)
    await applyTemplate(opts.template)
    return
  }

  // Auto-generate .claude-setup.json if it doesn't exist
  const configCreated = ensureConfig()
  if (configCreated) {
    console.log(`${c.dim("Created .claude-setup.json — edit to tune token budgets and truncation rules")}`)
  }

  const state = await readState()
  const collected = await collectProjectFiles(process.cwd(), "deep")

  if (isEmptyProject(collected)) {
    const content = buildEmptyProjectCommand()

    // Token tracking
    const tokens = estimateTokens(content)
    const cost = estimateCost(tokens)

    if (dryRun) {
      console.log(c.bold("[DRY RUN] Would write:\n"))
      console.log(`  .claude/commands/stack-init.md (${content.length} chars, ~${tokens.toLocaleString()} tokens)`)
      console.log(`\n${c.dim("--- preview ---")}`)
      console.log(content.slice(0, 500))
      if (content.length > 500) console.log(c.dim(`\n... +${content.length - 500} chars`))

      section("Token cost estimate")
      console.log(`  ~${tokens.toLocaleString()} input tokens (${formatCost(cost)})`)
      return
    }

    ensureDir(".claude/commands")
    writeFileSync(".claude/commands/stack-init.md", content, "utf8")
    writeFileSync(".claude/commands/stack-sync.md", buildBootstrapSync(), "utf8")
    installBootstrapCommands(".claude/commands")
    installMarketplaceFetcher()
    await updateManifest("init", collected, { estimatedTokens: tokens, estimatedCost: cost })
    installTokenHook()

    // Create initial snapshot — collectFilesForSnapshot scans all .claude/ automatically
    const cwd = process.cwd()
    const snapshotFiles = collectFilesForSnapshot(cwd, Object.keys(collected.configs))
    createSnapshot(cwd, "init", snapshotFiles, { summary: "initial setup (empty project)" })

    console.log(`
${c.green("✅")} New project detected.

Open Claude Code and run:
   ${c.cyan("/stack-init")}

Claude Code will ask 3 questions, then set up your environment.
    `)

    return
  }

  // Standard init — atomic steps + orchestrator
  const steps = buildAtomicSteps(collected, state)
  const orchestrator = buildOrchestratorCommand(steps)

  // Token tracking — sum all steps
  const totalContent = steps.map(s => s.content).join("\n") + "\n" + orchestrator
  const tokens = estimateTokens(totalContent)
  const cost = estimateCost(tokens)

  if (dryRun) {
    console.log(c.bold("[DRY RUN] Would write:\n"))
    for (const step of steps) {
      const stepTokens = estimateTokens(step.content)
      console.log(`  .claude/commands/${step.filename} (${step.content.length} chars, ~${stepTokens.toLocaleString()} tokens)`)
    }
    console.log(`  .claude/commands/stack-init.md (orchestrator)`)
    console.log(`\n${c.dim(`Total: ~${tokens.toLocaleString()} tokens across ${steps.length} files`)}`)

    section("Token cost estimate")
    console.log(`  ~${tokens.toLocaleString()} input tokens (${formatCost(cost)})`)
    return
  }

  ensureDir(".claude/commands")
  for (const step of steps) {
    writeFileSync(join(".claude/commands", step.filename), step.content, "utf8")
  }
  writeFileSync(".claude/commands/stack-init.md", orchestrator, "utf8")
  writeFileSync(".claude/commands/stack-sync.md", buildBootstrapSync(), "utf8")
  installBootstrapCommands(".claude/commands")
  installMarketplaceFetcher()
  await updateManifest("init", collected, { estimatedTokens: tokens, estimatedCost: cost })
  installTokenHook()

  // Create initial snapshot — collectFilesForSnapshot scans all .claude/ automatically
  const cwd = process.cwd()
  const snapshotFiles = collectFilesForSnapshot(cwd, Object.keys(collected.configs))
  createSnapshot(cwd, "init", snapshotFiles, {
    summary: `${steps.length - 1} atomic steps generated`,
  })

  console.log(`
${c.green("✅")} Ready. Open Claude Code and run:
   ${c.cyan("/stack-init")}

Runs ${steps.length - 1} atomic steps. If one fails, re-run only that step.
  `)

}
